FROM resin/%%RESIN_MACHINE_NAME%%-node

WORKDIR /usr/src/app

RUN apt-get install git-all

COPY package.json ./package.json
RUN npm install

COPY . /usr/src/app

RUN chmod +x entry.sh

CMD [ "./entry.sh" ]